# Generated by Django 3.2.7 on 2021-10-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_lib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_genre',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
