# Generated by Django 3.2.7 on 2021-10-24 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rnumgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcode', models.CharField(db_index=True, max_length=5, unique=True, verbose_name='Employee Report code')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roperator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rnumgen.employee', verbose_name='Report Operator')),
            ],
        ),
        migrations.DeleteModel(
            name='Rnuma',
        ),
    ]
